@startuml
!pragma teoz true
participant Browser as b
participant Merchant as m
participant Scanpay as sp
participant MobilePay as mp
participant Acquirer as acq
b -> m ++ : Go to payment
m -> sp ++ : Create payment link
m <-- sp -- : URL
b <-- m -- : //Redirect to payment window//
deactivate m
activate b #LightBlue
group This negotiation happens automatically [?go=mobilepay]
    b -> sp ++ : Go to MobilePay
    sp -> mp ++ : Create session
    sp <-- mp -- : Session data
    b <-- sp -- : //Redirect to MobilePay window//
    activate b #Teal
end
mp -> mp
note left #LightCyan : Payer swipes in MobilePay app.
mp -> sp : Credit card data
sp -> acq ++ : Credit card data
note over sp, mp #LightSalmon
Strong Customer Authentication
can be performed here //(if necessary)//
See SCA diagram for details.
end note
/ note over m
Authorizing means reserving
money on the cardholders
bank account.
end note
sp <-- acq -- : Authorization data
sp -> mp ++ : Transaction authorized
sp <-- mp -- : OK
m <- sp : Ping
& mp -> mp : \t
note left #LightCyan : MobilePay app shows\ntransaction complete.
b <- mp : //Redirect back to payment window//
deactivate b
b -> b : //Redirect to// ""successurl""
deactivate b

& group Seq
    m -> sp ++ : Get new changes
    m <-- sp -- : Transaction data
end
m -> sp ++ : Capture transaction
sp -> acq ++ : Authorization data
note over m
Capturing means transferring money
from the cardholder's bank account
to the merchant's bank account.
end note
sp <-- acq -- : Capture data
m <-- sp -- : Success
sp -> m : Ping
sp -> mp ++ : Transaction captured
sp <-- mp -- : OK
mp -> mp
note left #LightCyan : MobilePay app shows money has been transferred
@enduml
