@startuml
!pragma teoz true
participant Browser as b
participant Scanpay as sp
participant "3-D Secure" as sca
participant Acquirer as acq
activate b #LightBlue
b -> sp ++ : Credit card information
group Acquirers can enforce SCA
sp -> acq ++ : Credit card information
sp <-- acq -- : SCA required
end
note right of sp
Scanpay has systems to enforce SCA without
an acquirer's involvement, eg. for dissuading
and combatting fraudulent use.
end note
sp -> sca ++ : Credit card number (**""Prep""**)
sp <-- sca -- : URL
b <-- sp -- : //Insert iframe to fingerprint browser//
b -> sp : Fingerprinting done
activate sp #LightCyan
activate sp #LavenderBlush
sp -> sca : Authentication request (**""AReq""**)
activate sca #LavenderBlush
activate sca #LightCyan
alt #LightCyan Frictionless flow
    sp <-- sca -- : Authentication data (**""ARes""**)
else #LavenderBlush <back:LavenderBlush>Challenge flow</back>
    sp <-- sca -- : Challenge required (**""ARes""**)
    b <-- sp -- : //Redirect to card issuer challenge// (**""CReq""**)
    activate b #Pink
    b -> sca ++ : Issuer-specific challenge information
    note over sp
        The challenge performed is specific to the card issuer.
        For example, for Nets the challenge is a choice of MitID
        verification or password + SMS code authentication.
    end note
    b <-- sca -- : //Redirect back to payment window//
    deactivate b
    b -> sp ++ #LavenderBlush : Challenge result (**""CRes""**)
    sp -> sca ++ : Get authentication data
    sp <-- sca -- : Authentication data (**""RReq""**)
end
sp -> acq ++ : Card + authentication data
sp <-- acq -- : Authorization data
b <-- sp : Success
deactivate sp
deactivate sp
@enduml
