@startuml
!pragma teoz true
participant Browser as b
participant Merchant as m
participant Scanpay as sp
participant "Apple Pay" as ap
participant Acquirer as acq
b -> m ++ : Go to payment
m -> sp ++ : Create payment link
m <-- sp -- : URL
b <-- m -- : //Redirect to payment window//
activate b #LightBlue
b -> sp ++ : Create Apple Pay session
note right of b
For security reasons this request must be
precipitated by a button click. The browser
enforces this very strictly, and this is what
informs the somewhat kludgy interface.
end note
& sp -> ap ++ : Create session
sp <-- ap -- : Session data
b <-- sp -- : Session data
b -> ap ++ : Get token
note right of b
A popup appears from the browser itself, prompting the payer to
verify the payment details before sending the payment data.
end note
b <-- ap -- : Encrypted and signed token
b -> sp ++ : Encrypted and signed token
sp -> sp : Decrypt token
sp -> acq ++ : Card token data
note over m #LightSalmon
Strong Customer Authentication
can be performed here //(if necessary)//
See SCA diagram for details.
end note
note over m
Authorizing means reserving money
on the cardholders bank account.
end note
sp <-- acq -- : Authorization data
b <-- sp -- : Success
m <- sp : Ping
b -> b : //Redirect to// ""successurl""
deactivate b

& group Seq
    m -> sp ++ : Get new changes
    m <-- sp -- : Transaction data
end
m -> sp ++ : Capture transaction
sp -> acq ++ : Authorization data
note over m
Capturing means transferring money
from the cardholder's bank account
to the merchant's bank account.
end note
sp <-- acq -- : Capture data
m <-- sp -- : Success
sp -> m : Ping
@enduml
