@startuml
!pragma teoz true
participant Browser as b
participant Merchant as m
participant Scanpay as sp
participant Acquirer as acq
b -> m ++ : Go to payment
m -> sp ++ : Create payment link
m <-- sp -- : URL
b <-- m -- : //Redirect to payment window//
activate b #LightBlue
b -> sp ++ : Credit card information
sp -> acq ++ : Credit card information
note over m #LightSalmon
Strong Customer Authentication
can be performed here //(if necessary)//
See SCA diagram for details.
end note
note over m
Authorizing means reserving money
on the cardholders bank account.
end note
sp <-- acq -- : Authorization data
b <-- sp -- : Success
sp -> m : Ping
b -> b -- : //Redirect to// ""successurl""
& group Seq
    m -> sp ++ : Get new changes
    m <-- sp -- : Transaction data
end
m -> sp ++ : Capture transaction
sp -> acq ++ : Authorization data
note over m
Capturing means transferring money
from the cardholder's bank account
to the merchant's bank account.
end note
sp <-- acq -- : Capture data
m <-- sp -- : Success
sp -> m : Ping
@enduml
